### ISSUE TITLE
Unordered list elements are joined into a single line upon save

### ISSUE THREAD

**Issue by bentolor** [shurcooL/atom-markdown-format#27] opened 2015-11-02 13:27 UTC
On saving the following markdown text:

```
# h1
## h2

A sentence.

- topic 1
- topic 2
```

this plugin produces the following result, in which the unordered list becomes broken.

```
h1
==

h2
--

A sentence. - topic 1 - topic 2
```

**Comment by dmitshur** [comment] 2015-11-04 07:52
That is unexpected. That input should definitely work and get correctly formatted as an unordered list.

I can't reproduce it when I tried it with `markdownfmt` binary directly.

Perhaps you have an older version, or it's some strange conflict with another package you have running?

However, this Atom package is now deprecated and will be removed soon. Please find motivation [here](https://github.com/shurcooL/atom-markdown-format/pull/26). So I'll close this.

**Closed as completed by dmitshur** 2015-11-04 07:52 UTC
