### ISSUE TITLE
Workspace.eachEditor is deprecated.

### ISSUE THREAD

**Issue by Jamestt** [shurcooL/atom-markdown-format#20] opened 2015-05-05 17:52 UTC
Use Workspace::observeTextEditors instead
```
Workspace.eachEditor (/opt/atom/resources/app.asar/src/workspace.js:965:7)
new MarkdownFormat (/home/jamestt/.atom/packages/markdown-format/lib/markdown-format.coffee:5:19)
Object.activate (/home/jamestt/.atom/packages/markdown-format/lib/markdown-format.coffee:19:26)
Package.activateNow (/opt/atom/resources/app.asar/src/package.js:222:19)
```

**Comment by shurcooL** [comment] 2015-05-05 19:42
Duplicate of #18.

**Closed by shurcooL** 2015-05-05 19:42 UTC
