### ISSUE TITLE
TextBuffer.on is deprecated.

### ISSUE THREAD

**Issue by Jamestt** [shurcooL/atom-markdown-format#19] opened 2015-05-05 17:51 UTC
Use TextBuffer::onWillSave instead. A TextBuffer instance is no longer provided as a callback argument.
```
TextBuffer.on (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1179:16)
Atom.subscribeWith (/opt/atom/resources/app.asar/node_modules/emissary/lib/subscriber.js:28:32)
Atom.subscribe (/opt/atom/resources/app.asar/node_modules/emissary/lib/subscriber.js:63:21)
MarkdownFormat.handleSave (/home/jamestt/.atom/packages/markdown-format/lib/markdown-format.coffee:13:9)
```

**Comment by shurcooL** [comment] 2015-05-05 19:42
Duplicate of #18.

**Closed by shurcooL** 2015-05-05 19:42 UTC
