### ISSUE TITLE
Workspace.getEditors is deprecated.

### ISSUE THREAD

**Issue by Jamestt** [shurcooL/atom-markdown-format#21] opened 2015-05-05 17:52 UTC
Use Workspace::getTextEditors instead
```
Workspace.getEditors (/opt/atom/resources/app.asar/src/workspace.js:977:7)
Workspace.eachEditor (/opt/atom/resources/app.asar/src/workspace.js:966:20)
new MarkdownFormat (/home/jamestt/.atom/packages/markdown-format/lib/markdown-format.coffee:5:19)
Object.activate (/home/jamestt/.atom/packages/markdown-format/lib/markdown-format.coffee:19:26)
```

**Comment by shurcooL** [comment] 2015-05-05 19:42
Duplicate of #18.

**Closed by shurcooL** 2015-05-05 19:42 UTC
