### ISSUE TITLE
Failed to activate the markdown-format package

### ISSUE THREAD

**Issue by ninliu** [shurcooL/atom-markdown-format#17] opened 2015-04-09 03:41 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [markdown-format](https://github.com/shurcooL/atom-markdown-format) package, v2.5.0

### Stack Trace

Failed to activate the markdown-format package

```
At undefined is not a function

TypeError: undefined is not a function
    at new MarkdownFormat (/Users/liuning/.atom/packages/markdown-format/lib/markdown-format.coffee:8:22)
    at Object.module.exports.activate (/Users/liuning/.atom/packages/markdown-format/lib/markdown-format.coffee:37:36)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:302:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:395:46)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:634:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:54:25)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-format",
      "xml-formatter",
      "pretty-json"
    ]
  }
}
```

### Installed Packages

```coffee
# User
format-sql, v0.2.0
language-protobuf, v0.3.0
markdown-format, v2.5.0

# Dev
No dev packages
```

**Comment by shurcooL** [comment] 2015-04-09 05:04
Sorry, I haven't used Atom in a while, they've probably changed stuff so this package needs updating. I'll try to take a look sometime.

**Comment by shurcooL** [comment] 2015-04-19 04:54
@ninliu Hmm, I just updated to latest Atom (0.192.0), and I am seeing a deprecation warning, but aside from that, markdown-format 2.5.0 loads and works okay.

Any ideas why I can't reproduce? I'm on OS X 10.10.3. Can you try again with Atom 0.192.0 please (your report was with 0.190.0)?

**Comment by uncleserb** [comment] 2015-05-04 12:47
@shurcooL FYI, I'm getting the same error with Atom 0.196.0 on OS X 10.10.4.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.4
**Thrown From**: [markdown-format](https://github.com/shurcooL/atom-markdown-format) package, v2.5.0

### Stack Trace

Failed to activate the markdown-format package

```
At undefined is not a function

TypeError: undefined is not a function
    at new MarkdownFormat (/Users/paul/.atom/packages/markdown-format/lib/markdown-format.coffee:8:22)
    at Object.module.exports.activate (/Users/paul/.atom/packages/markdown-format/lib/markdown-format.coffee:37:36)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:623:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:23)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:38:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "linter-tidy",
      "linter-csslint"
    ],
    "projectHome": "/Users/Paul/Dropbox/Sites/"
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.6
autocomplete-plus, v2.12.1
git-projects, v1.13.0
highlight-line, v0.10.2
language-csharp, v0.5.0
linter, v0.12.1
markdown-format, v2.5.0
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by shurcooL** [comment] 2015-05-06 09:26
Hi @uncleserb and @ninliu,

I've published [markdown-format@v2.5.1](https://github.com/shurcooL/atom-markdown-format/releases/tag/v2.5.1) that fixes use of deprecated APIs. You can try updating and see if it helps.

**Comment by uncleserb** [comment] 2015-05-06 16:23
Fixed on my side @shurcooL ; many thanks!

**Comment by shurcooL** [comment] 2015-05-07 08:02
Great, I'll close. Feel free reopen if issue persists.

**Closed by shurcooL** 2015-05-07 08:02 UTC
